import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'

const ibm_plex_sans = IBM_Plex_Sans({weight:'500',subsets:['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.className}>{children}</body>
    </html>
  )
}
